version: "3.7"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${NGINX_CONTAINER_NAME}
    depends_on:
      - php
      - mysql
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: ${SERVICE_TAGS}
      SERVICE_NAME: ${SERVICE_NAME}
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PHP_CONTAINER_NAME}
    volumes:
      - ./src:/var/www/html
    ports:
      - "${PHP_PORT}:${PHP_PORT}"
    networks:
      - laravel

  # composer:
  #   image: composer:latest
  #   container_name: ${COMPOSER_CONTAINER_NAME}
  #   volumes:
  #     - ./src:/var/www/html
  #   working_dir: /var/www/html
  #   networks:
  #     - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    depends_on:
      - mysql
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - laravel

  # artisan:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: ${ARTISAN_CONTAINER_NAME}
  #   volumes:
  #     - ./src:/var/www/html
  #   depends_on:
  #     - mysql
  #   working_dir: /var/www/html
  #   entrypoint: ["/var/www/html/artisan"]
  #   networks:
  #     - laravel

  # npm:
  #   image: node:14.17.6
  #   container_name: npm
  #   volumes:
  #     - ./src:/var/www/html
  #   working_dir: /var/www/html
  #   entrypoint: ["npm"]
  #   networks:
  #     - laravel
